export type Gender = 'Male' | 'Female' | 'Other';
export type MaritalStatus = 'Single' | 'Divorced' | 'Widowed';
export type FamilyType = 'Nuclear' | 'Joint' | 'Extended';
export type DietPreference = 'Vegetarian' | 'Non-Vegetarian' | 'Eggetarian' | 'Vegan';
export type Habit = 'Non-smoker' | 'Smoker' | 'Occasional smoker' | 'Non-drinker' | 'Drink socially';
export type Religion = 'Hindu' | 'Muslim' | 'Christian' | 'Sikh' | 'Jain' | 'Buddhist' | 'Other';
export type Caste = 'Brahmin' | 'Kshatriya' | 'Vaishya' | 'Shudra' | 'OBC' | 'General' | 'Other';

export type Customer = {
  id: string;
  firstName: string;
  lastName: string;
  gender: Gender;
  dob: string;
  country: string;
  city: string;
  height: number;
  email: string;
  phone: string;
  undergradCollege: string;
  degree: string;
  income: number;
  company: string;
  designation: string;
  maritalStatus: MaritalStatus;
  languages: string[];
  siblings: string;
  caste: Caste;
  religion: Religion;
  wantKids: boolean;
  openToRelocate: boolean;
  openToPets: boolean;
  horoscopeSign: string;
  manglikStatus: 'Yes' | 'No' | 'Partial';
  familyType: FamilyType;
  dietPreference: DietPreference;
  habits: Habit[];
  status: 'New' | 'In Progress' | 'Matched';
  notes?: Array<{ id: string; message: string; createdAt: string }>;
};
